apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: default  # Or whatever namespace you're using
data:
  prometheus-alert-rules.yaml: |
    groups:
      - name: OnlineBoutiqueAlerts
        rules:
          - alert: FrontendServiceDown
            expr: probe_success{job="blackbox-frontend"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Frontend service is down"
              description: "The frontend service has been down for more than 2 minutes."
          - alert: CartserviceDown
            expr: probe_success{job="blackbox-cartservice"} == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Cartservice is down"
              description: "The cartservice has been down for more than 2 minutes."
          - alert: HighFrontendResponseTime
            expr: probe_duration_seconds{job="blackbox-frontend"} > 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High response time for frontend"
              description: "The frontend service has a response time higher than 1 second for more than 1 minute."
          - alert: HighCartserviceResponseTime
            expr: probe_duration_seconds{job="blackbox-cartservice"} > 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High response time for cartservice"
              description: "The cartservice has a response time higher than 1 second for more than 1 minute."

