apiVersion: v1
kind: ConfigMap
metadata:
  name: verifier-config
  labels:
    app: vermon

data:
  verifiers_config.json: |
    {
      "verifiers": [
        "R1.1_latency",
        "R1.2_empty_cart",
        "R1.3_failure_rate",
        "R1.4_resource_usage"
      ]
    }
